name: Meroshare automation
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download the build folders
        uses: actions/download-artifact@v3
        with:
          name: build
          path: build
      - name: Use .env files
        env:
            ENV_FILE: ${{ secrets.ENV }}
            CYPRESS_PROJECT_ID: ${{ secrets.PROJECT_ID }}
            CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            echo "$ENV_FILE" > .env
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6

            
